Document: epics-snmp
Title: Debian epics-snmp Manual
Author: <insert document author here>
Abstract: This manual describes what epics-snmp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/epics-snmp/epics-snmp.sgml.gz

Format: postscript
Files: /usr/share/doc/epics-snmp/epics-snmp.ps.gz

Format: text
Files: /usr/share/doc/epics-snmp/epics-snmp.text.gz

Format: HTML
Index: /usr/share/doc/epics-snmp/html/index.html
Files: /usr/share/doc/epics-snmp/html/*.html
